//! The post component vocabulary, registered through `#[post_component]`.

pub mod callout;
pub mod counter;

// Per-post modules generated by build.rs from content/blog/*/components.rs.
include!(concat!(env!("OUT_DIR"), "/post_components.rs"));
